-- 1. KHUVUC
BULK INSERT KHUVUC
FROM 'D:\ShuShiXDB\KHUVUC.csv'
WITH (
    FIRSTROW=2,
    FIELDTERMINATOR=',',
    ROWTERMINATOR='\n',
    CODEPAGE='65001',
    FORMAT='CSV'
);

-- 2. BOPHAN
BULK INSERT BOPHAN
FROM 'D:\ShuShiXDB\BOPHAN.csv'
WITH (
    FIRSTROW=2,
    FIELDTERMINATOR=',',
    ROWTERMINATOR='\n',
    CODEPAGE='65001',
    FORMAT='CSV'
);

-- 3. MUCTHUCDON
BULK INSERT MUCTHUCDON
FROM 'D:\ShuShiXDB\MUCTHUCDON.csv'
WITH (
    FIRSTROW=2,
    FIELDTERMINATOR=',',
    ROWTERMINATOR='\n',
    CODEPAGE='65001',
    FORMAT='CSV'
);

-- 4. CHINHANH
BULK INSERT CHINHANH
FROM 'D:\ShuShiXDB\CHINHANH.csv'
WITH (
    FIRSTROW=2,
    FIELDTERMINATOR=',',
    ROWTERMINATOR='\n',
    CODEPAGE='65001',
    FORMAT='CSV'
);

-- 5. NHANVIEN
BULK INSERT NHANVIEN
FROM 'D:\ShuShiXDB\NHANVIEN.csv'
WITH (
    FIRSTROW=2,
    FIELDTERMINATOR=',',
    ROWTERMINATOR='\n',
    CODEPAGE='65001',
    FORMAT='CSV'
);

-- 6. LICHSULAMVIEC
BULK INSERT LICHSULAMVIEC
FROM 'D:\ShuShiXDB\LICHSULAMVIEC.csv'
WITH (
    FIRSTROW=2,
    FIELDTERMINATOR=',',
    ROWTERMINATOR='\n',
    CODEPAGE='65001',
    FORMAT='CSV'
);

-- 7. KHACHHANG
BULK INSERT KHACHHANG
FROM 'D:\ShuShiXDB\KHACHHANG.csv'
WITH (
    FIRSTROW=2,
    FIELDTERMINATOR=',',
    ROWTERMINATOR='\n',
    CODEPAGE='65001',
    FORMAT='CSV'
);

-- 8. MONAN
BULK INSERT MONAN
FROM 'D:\ShuShiXDB\MONAN.csv'
WITH (
    FIRSTROW=2,
    FIELDTERMINATOR=',',
    ROWTERMINATOR='\n',
    CODEPAGE='65001',
    FORMAT='CSV'
);

-- 9. THETHANHVIEN
BULK INSERT THETHANHVIEN
FROM 'D:\ShuShiXDB\THETHANHVIEN.csv'
WITH (
    FIRSTROW=2,
    FIELDTERMINATOR=',',
    ROWTERMINATOR='\n',
    CODEPAGE='65001',
    FORMAT='CSV'
);

-- 10. LICHSUTRUYCAP
BULK INSERT LICHSUTRUYCAP
FROM 'D:\ShuShiXDB\LICHSUTRUYCAP.csv'
WITH (
    FIRSTROW=2,
    FIELDTERMINATOR=',',
    ROWTERMINATOR='\n',
    CODEPAGE='65001',
    FORMAT='CSV'
);

-- 11. BAN
BULK INSERT BAN
FROM 'D:\ShuShiXDB\BAN.csv'
WITH (
    FIRSTROW=2,
    FIELDTERMINATOR=',',
    ROWTERMINATOR='\n',
    CODEPAGE='65001',
    FORMAT='CSV'
);

-- 12. CHINHANH_MON
BULK INSERT CHINHANH_MON
FROM 'D:\ShuShiXDB\CHINHANH_MON.csv'
WITH (
    FIRSTROW=2,
    FIELDTERMINATOR=',',
    ROWTERMINATOR='\n',
    CODEPAGE='65001',
    FORMAT='CSV'
);

-- 13. DATBAN
BULK INSERT DATBAN
FROM 'D:\ShuShiXDB\DATBAN.csv'
WITH (
    FIRSTROW=2,
    FIELDTERMINATOR=',',
    ROWTERMINATOR='\n',
    CODEPAGE='65001',
    FORMAT='CSV'
);

-- 14. THONGTINPHIEUDATMON
BULK INSERT THONGTINPHIEUDATMON
FROM 'D:\ShuShiXDB\THONGTINPHIEUDATMON.csv'
WITH (
    FIRSTROW=2,
    FIELDTERMINATOR=',',
    ROWTERMINATOR='\n',
    CODEPAGE='65001',
    FORMAT='CSV'
);

-- 15. CHITIETPHIEUDATMON
BULK INSERT CHITIETPHIEUDATMON
FROM 'D:\ShuShiXDB\CHITIETPHIEUDATMON.csv'
WITH (
    FIRSTROW=2,
    FIELDTERMINATOR=',',
    ROWTERMINATOR='\n',
    CODEPAGE='65001',
    FORMAT='CSV'
);

-- 16. HOADON
BULK INSERT HOADON
FROM 'D:\ShuShiXDB\HOADON.csv'
WITH (
    FIRSTROW=2,
    FIELDTERMINATOR=',',
    ROWTERMINATOR='\n',
    CODEPAGE='65001',
    FORMAT='CSV'
);

-- 17. DANHGIA
BULK INSERT DANHGIA
FROM 'D:\ShuShiXDB\DANHGIA.csv'
WITH (
    FIRSTROW=2,
    FIELDTERMINATOR=',',
    ROWTERMINATOR='\n',
    CODEPAGE='65001',
    FORMAT='CSV'
);
