USE sushiX;
GO

-- Thêm PRIMARY KEY, FOREIGN KEY, CHECK, UNIQUE, DEFAULT bằng ALTER TABLE
-- Giả sử tất cả các bảng đã tồn tại nhưng chưa có bất kỳ constraint nào.

-------------------
-- KHUVUC
-------------------
ALTER TABLE KHUVUC
ADD CONSTRAINT PK_KHUVUC PRIMARY KEY (MaKhuVuc);

-------------------
-- CHINHANH
-------------------
ALTER TABLE CHINHANH
ADD CONSTRAINT PK_CHINHANH PRIMARY KEY (MaChiNhanh);

ALTER TABLE CHINHANH
ADD CONSTRAINT FK_CHINHANH_KHUVUC FOREIGN KEY (MaKhuVuc) REFERENCES KHUVUC(MaKhuVuc);

ALTER TABLE CHINHANH
ADD CONSTRAINT DF_CHINHANH_CoBaiDoXeMay DEFAULT(0) FOR CoBaiDoXeMay,
    CONSTRAINT DF_CHINHANH_CoBaiDoOto DEFAULT(0) FOR CoBaiDoOto;

-------------------
-- BOPHAN
-------------------
ALTER TABLE BOPHAN
ADD CONSTRAINT PK_BOPHAN PRIMARY KEY (MaBoPhan);

ALTER TABLE BOPHAN
ADD CONSTRAINT CHK_BOPHAN_LUONG CHECK (Luong >= 0);

-------------------
-- NHANVIEN
-------------------
ALTER TABLE NHANVIEN
ADD CONSTRAINT PK_NHANVIEN PRIMARY KEY (MaNhanVien);

ALTER TABLE NHANVIEN
ADD CONSTRAINT FK_NHANVIEN_BOPHAN FOREIGN KEY (MaBoPhan) REFERENCES BOPHAN(MaBoPhan),
    CONSTRAINT FK_NHANVIEN_CHINHANH FOREIGN KEY (MaChiNhanh) REFERENCES CHINHANH(MaChiNhanh),
    CONSTRAINT CHK_NHANVIEN_GioiTinh CHECK (GioiTinh IN (N'Nam', N'Nữ', N'Khác'));

-------------------
-- LICHSULAMVIEC
-------------------
ALTER TABLE LICHSULAMVIEC
ADD CONSTRAINT PK_LICHSULAMVIEC PRIMARY KEY (MaNhanVien, MaChiNhanh, NgayBatDau);

ALTER TABLE LICHSULAMVIEC
ADD CONSTRAINT FK_LICHSULAMVIEC_NHANVIEN FOREIGN KEY (MaNhanVien) REFERENCES NHANVIEN(MaNhanVien),
    CONSTRAINT FK_LICHSULAMVIEC_CHINHANH FOREIGN KEY (MaChiNhanh) REFERENCES CHINHANH(MaChiNhanh);

-------------------
-- KHACHHANG
-------------------
ALTER TABLE KHACHHANG
ADD CONSTRAINT PK_KHACHHANG PRIMARY KEY (MaKhachHang),
    CONSTRAINT UQ_KHACHHANG_SoCCCD UNIQUE(SoCCCD),
    CONSTRAINT CHK_KHACHHANG_GioiTinh CHECK(GioiTinh IN (N'Nam', N'Nữ', N'Khác'));

ALTER TABLE KHACHHANG
ADD CONSTRAINT DF_KHACHHANG_KhachOnline DEFAULT(0) FOR KhachOnline;

-------------------
-- THETHANHVIEN
-------------------
ALTER TABLE THETHANHVIEN
ADD CONSTRAINT PK_THETHANHVIEN PRIMARY KEY (MaSoThe),
    CONSTRAINT FK_THETHANHVIEN_KHACHHANG FOREIGN KEY (MaKhachHang) REFERENCES KHACHHANG(MaKhachHang),
    CONSTRAINT CHK_THETHANHVIEN_DiemTichLuy CHECK(DiemTichLuy >= 0),
    CONSTRAINT CHK_THETHANHVIEN_LoaiThe CHECK (LoaiThe IN (N'Member', N'Silver', N'Gold')),
    CONSTRAINT CHK_THETHANHVIEN_TinhTrangThe CHECK (TinhTrangThe IN (N'Active', N'Inactive'));

ALTER TABLE THETHANHVIEN
ADD CONSTRAINT DF_THETHANHVIEN_TinhTrangThe DEFAULT('Active') FOR TinhTrangThe,
    CONSTRAINT DF_THETHANHVIEN_DiemTichLuy DEFAULT(0) FOR DiemTichLuy;

-------------------
-- LICHSUTRUYCAP
-------------------
ALTER TABLE LICHSUTRUYCAP
ADD CONSTRAINT FK_LICHSUTRUYCAP_KHACHHANG FOREIGN KEY (MaKhachHang) REFERENCES KHACHHANG(MaKhachHang),
    CONSTRAINT CHK_LICHSUTRUYCAP_ThoiGian CHECK (ThoiGianTruyCap >= 0);

-------------------
-- MUCTHUCDON
-------------------
ALTER TABLE MUCTHUCDON
ADD CONSTRAINT PK_MUCTHUCDON PRIMARY KEY (MaMucThucDon);

-------------------
-- MONAN
-------------------
ALTER TABLE MONAN
ADD CONSTRAINT PK_MONAN PRIMARY KEY (MaMon),
    CONSTRAINT FK_MONAN_MUCTHUCDON FOREIGN KEY (MaMucThucDon) REFERENCES MUCTHUCDON(MaMucThucDon),
    CONSTRAINT CHK_MONAN_GiaTien CHECK (GiaTien >= 0);

-------------------
-- CHINHANH_MON
-------------------
ALTER TABLE CHINHANH_MON
ADD CONSTRAINT PK_CHINHANH_MON PRIMARY KEY (MaChiNhanh, MaMon),
    CONSTRAINT FK_CHINHANH_MON_CHINHANH FOREIGN KEY (MaChiNhanh) REFERENCES CHINHANH(MaChiNhanh),
    CONSTRAINT FK_CHINHANH_MON_MONAN FOREIGN KEY (MaMon) REFERENCES MONAN(MaMon);

ALTER TABLE CHINHANH_MON
ADD CONSTRAINT DF_CHINHANH_MON_CoPhucVu DEFAULT(0) FOR CoPhucVu;

-------------------
-- BAN
-------------------
ALTER TABLE BAN
ADD CONSTRAINT PK_BAN PRIMARY KEY (MaChiNhanh, STTBan),
    CONSTRAINT FK_BAN_CHINHANH FOREIGN KEY (MaChiNhanh) REFERENCES CHINHANH(MaChiNhanh);

-------------------
-- DATBAN
-------------------
ALTER TABLE DATBAN
ADD CONSTRAINT PK_DATBAN PRIMARY KEY(MaDatBan),
    CONSTRAINT FK_DATBAN_KHACHHANG FOREIGN KEY(MaKhachHang) REFERENCES KHACHHANG(MaKhachHang),
    CONSTRAINT FK_DATBAN_BAN FOREIGN KEY(MaChiNhanh, STTBan) REFERENCES BAN(MaChiNhanh, STTBan),
    CONSTRAINT CHK_DATBAN_SoLuongKhach CHECK (SoLuongKhach > 0);

-------------------
-- THONGTINPHIEUDATMON
-------------------
ALTER TABLE THONGTINPHIEUDATMON
ADD CONSTRAINT PK_THONGTINPHIEUDATMON PRIMARY KEY(MaPhieu),
    CONSTRAINT FK_THONGTINPHIEUDATMON_BAN FOREIGN KEY(MaChiNhanh, STTBan) REFERENCES BAN(MaChiNhanh, STTBan),
    CONSTRAINT FK_THONGTINPHIEUDATMON_NHANVIEN FOREIGN KEY(MaNV) REFERENCES NHANVIEN(MaNhanVien),
    CONSTRAINT FK_THONGTINPHIEUDATMON_KHACHHANG FOREIGN KEY(MaKH) REFERENCES KHACHHANG(MaKhachHang);

-------------------
-- CHITIETPHIEUDATMON
-------------------
ALTER TABLE CHITIETPHIEUDATMON
ADD CONSTRAINT PK_CHITIETPHIEUDATMON PRIMARY KEY(MaPhieu, STT),
    CONSTRAINT FK_CHITIETPHIEUDATMON_PHIEU FOREIGN KEY(MaPhieu) REFERENCES THONGTINPHIEUDATMON(MaPhieu),
    CONSTRAINT FK_CHITIETPHIEUDATMON_MONAN FOREIGN KEY(MaMon) REFERENCES MONAN(MaMon),
    CONSTRAINT CHK_CHITIETPHIEUDATMON_SoLuong CHECK(SoLuong > 0);

-------------------
-- HOADON
-------------------
ALTER TABLE HOADON
ADD CONSTRAINT PK_HOADON PRIMARY KEY(MaHoaDon),
    CONSTRAINT FK_HOADON_THONGTINPHIEU FOREIGN KEY(MaPhieu) REFERENCES THONGTINPHIEUDATMON(MaPhieu),
    CONSTRAINT CHK_HOADON_TongTien CHECK (TongTien >= 0),
    CONSTRAINT CHK_HOADON_TienGiamGia CHECK (TienGiamGia >= 0);

ALTER TABLE HOADON
ADD CONSTRAINT DF_HOADON_TienGiamGia DEFAULT(0) FOR TienGiamGia;

-------------------
-- DANHGIA
-------------------
ALTER TABLE DANHGIA
ADD CONSTRAINT PK_DANHGIA PRIMARY KEY(MaHoaDon),
    CONSTRAINT FK_DANHGIA_HOADON FOREIGN KEY(MaHoaDon) REFERENCES HOADON(MaHoaDon),
    CONSTRAINT CHK_DANHGIA_DiemPhucVu CHECK (DiemPhucVu BETWEEN 0 AND 10),
    CONSTRAINT CHK_DANHGIA_DiemViTri CHECK (DiemViTri BETWEEN 0 AND 10),
    CONSTRAINT CHK_DANHGIA_DiemChatLuongMonAn CHECK (DiemChatLuongMonAn BETWEEN 0 AND 10),
    CONSTRAINT CHK_DANHGIA_DiemGiaCa CHECK (DiemGiaCa BETWEEN 0 AND 10),
    CONSTRAINT CHK_DANHGIA_DiemKhongGian CHECK (DiemKhongGian BETWEEN 0 AND 10);

ALTER TABLE ACCOUNT
ADD CONSTRAINT FK_ACCOUNT_KHACHHANG FOREIGN KEY (MaKhachHang) REFERENCES KHACHHANG(MaKhachHang),
    CONSTRAINT FK_ACCOUNT_NHANVIEN FOREIGN KEY (MaNhanVien) REFERENCES NHANVIEN(MaNhanVien);
GO