ALTER TABLE THONGTINPHIEUDATMON DROP CONSTRAINT FK_THONGTINPHIEUDATMON_NHANVIEN;
ALTER TABLE CHINHANH DROP CONSTRAINT IF EXISTS FK_CHINHANH_QUANLY;

ALTER TABLE THONGTINPHIEUDATMON 
ADD CONSTRAINT FK_THONGTINPHIEUDATMON_NHANVIEN 
FOREIGN KEY (MaNV) REFERENCES NHANVIEN (MaNhanVien)
ON DELETE SET NULL;


-- Add constraint for QuanLyChiNhanh if not exists
ALTER TABLE CHINHANH
ADD CONSTRAINT FK_CHINHANH_QUANLY 
FOREIGN KEY (QuanLyChiNhanh) REFERENCES NHANVIEN(MaNhanVien)
ON DELETE SET NULL;